name: Build and deploy container app to Azure Web App - MercuryProject

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Convert username to lowercase
      run: echo "ACR_USERNAME=$(echo ${{ secrets.AzureAppService_ContainerUsername_9628f5370dd54a5d8c900708ca95907f }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: clientgpt.azurecr.io
        username: ${{ env.ACR_USERNAME }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e4b028d9b1d1459e892437284931af57 }}

    - name: Build and push container image to registry
      run: |
        IMAGE_TAG=clientgpt.azurecr.io/${{ env.ACR_USERNAME }}/internalclientgpt-mercury:${{ github.sha }}
        docker buildx build --file ../Dockerfile --tag $IMAGE_TAG --push .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'MercuryProject'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3368f836151b47e8a2802066068d1330 }}
        images: 'clientgpt.azurecr.io/${{ env.ACR_USERNAME }}/internalclientgpt-mercury:${{ github.sha }}'
