# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mercuryproject

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://clientgpt.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_8ad947f2e9b845d6943f37f75eaab908 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e9253402ef2b4e0d9f51b92c01e8d262 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: clientgpt.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8ad947f2e9b845d6943f37f75eaab908 }}/internalclientgptmercury:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mercuryproject'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4f3ac6363734408fa24b9ae992105a47 }}
        images: 'clientgpt.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8ad947f2e9b845d6943f37f75eaab908 }}/internalclientgptmercury:${{ github.sha }}'